# 7.1 Handling Missing Data

In [3]:
import pandas as pd
import numpy as np

In [4]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [5]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [6]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data = pd.Series(['aardvark', np.nan, None, 'avocado'])

In [8]:
string_data

0    aardvark
1         NaN
2         NaN
3     avocado
dtype: str

In [10]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [11]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [12]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [13]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

## 7.1.1 Filter Out Missing Data

In [14]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [15]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [17]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [18]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [19]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [20]:
data.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [21]:
data[4] = np.nan

In [22]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [23]:
data.dropna(axis='columns', how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [24]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [25]:
df.iloc[:4, 1] = np.nan

In [26]:
df.iloc[:2, 2] = np.nan

In [27]:
df

          0         1         2
0 -2.202629       NaN       NaN
1 -0.441929       NaN       NaN
2  0.985519       NaN -0.756773
3 -1.695017       NaN  0.306137
4 -0.713587  1.101915 -0.617419
5 -0.385391 -0.353960  0.297587
6 -0.937012 -0.514338  0.442205

In [28]:
df.dropna()

          0         1         2
4 -0.713587  1.101915 -0.617419
5 -0.385391 -0.353960  0.297587
6 -0.937012 -0.514338  0.442205

In [29]:
df.dropna(thresh=2)

          0         1         2
2  0.985519       NaN -0.756773
3 -1.695017       NaN  0.306137
4 -0.713587  1.101915 -0.617419
5 -0.385391 -0.353960  0.297587
6 -0.937012 -0.514338  0.442205

## 7.1.2 Imputing Missing Data

In [30]:
df.fillna(0)

          0         1         2
0 -2.202629  0.000000  0.000000
1 -0.441929  0.000000  0.000000
2  0.985519  0.000000 -0.756773
3 -1.695017  0.000000  0.306137
4 -0.713587  1.101915 -0.617419
5 -0.385391 -0.353960  0.297587
6 -0.937012 -0.514338  0.442205

In [31]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -2.202629  0.500000  0.000000
1 -0.441929  0.500000  0.000000
2  0.985519  0.500000 -0.756773
3 -1.695017  0.500000  0.306137
4 -0.713587  1.101915 -0.617419
5 -0.385391 -0.353960  0.297587
6 -0.937012 -0.514338  0.442205

In [32]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [34]:
df.iloc[2:, 1] = np.nan

In [35]:
df.iloc[4:, 2] = np.nan

In [36]:
df

          0         1         2
0 -0.366603 -0.651659 -0.412822
1  0.450905 -0.231817  0.951569
2  0.025547       NaN  0.948561
3 -0.179563       NaN  1.170577
4  1.765617       NaN       NaN
5  1.544303       NaN       NaN

In [38]:
df.ffill()

          0         1         2
0 -0.366603 -0.651659 -0.412822
1  0.450905 -0.231817  0.951569
2  0.025547 -0.231817  0.948561
3 -0.179563 -0.231817  1.170577
4  1.765617 -0.231817  1.170577
5  1.544303 -0.231817  1.170577

In [39]:
df.ffill(limit = 2)

          0         1         2
0 -0.366603 -0.651659 -0.412822
1  0.450905 -0.231817  0.951569
2  0.025547 -0.231817  0.948561
3 -0.179563 -0.231817  1.170577
4  1.765617       NaN  1.170577
5  1.544303       NaN  1.170577

In [40]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [41]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64