# 7.2 Data Conversion

## 7.2.1 Remove Duplicate Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

In [3]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [4]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [6]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [7]:
data['v1'] = range(7)

In [8]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [9]:
data.drop_duplicates(subset=['k1'])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [10]:
data.drop_duplicates(['k1', 'k2'], keep='last')

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

## 7.2.2 Using Functions or Mappings for Data Transformation

In [11]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'pastrami', 'corned beef', 'bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [12]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [13]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [14]:
data['animal'] = data['food'].map(meat_to_animal)

In [15]:
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [16]:
def get_animal(x):
    return meat_to_animal[x]

In [17]:
data['food'].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: str

## 7.2.3 Replacement value

In [18]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [19]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [20]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [21]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [22]:
data.replace([-999, -1000], [np.nan,  0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [23]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

## 7.2.4 Rename Axis Index

In [24]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [25]:
def transform(x):
    return x[:4].upper()

In [26]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='str')

In [27]:
data.index = data.index.map(transform)

In [28]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [29]:
data.rename(index=str.title, columns=str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [30]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

## 7.2.5 Discretization and Binning

In [31]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [32]:
bins = [18, 25, 35, 60, 100]

In [33]:
age_categories = pd.cut(ages, bins)

In [34]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [35]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [36]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [37]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [40]:
age_categories.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [41]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [42]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [43]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, str): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [44]:
data = np.random.uniform(size=10)

In [45]:
pd.cut(data, 4, precision=2)

[(0.74, 0.99], (0.74, 0.99], (0.5, 0.74], (0.26, 0.5], (0.5, 0.74], (0.014, 0.26], (0.74, 0.99], (0.5, 0.74], (0.74, 0.99], (0.5, 0.74]]
Categories (4, interval[float64, right]): [(0.014, 0.26] < (0.26, 0.5] < (0.5, 0.74] < (0.74, 0.99]]

In [46]:
data = np.random.standard_normal(1000)

In [47]:
quartiles = pd.qcut(data, 4, precision=2)

In [48]:
quartiles

[(0.045, 0.68], (0.68, 3.41], (-0.63, 0.045], (-3.0199999999999996, -0.63], (-3.0199999999999996, -0.63], ..., (0.68, 3.41], (-0.63, 0.045], (0.045, 0.68], (-0.63, 0.045], (-3.0199999999999996, -0.63]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.0199999999999996, -0.63] < (-0.63, 0.045] < (0.045, 0.68] < (0.68, 3.41]]

In [50]:
quartiles.value_counts(quartiles)

(-3.0199999999999996, -0.63]    250
(-0.63, 0.045]                  250
(0.045, 0.68]                   250
(0.68, 3.41]                    250
Name: count, dtype: int64

In [51]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.01, -1.289]     100
(-1.289, 0.0452]    400
(0.0452, 1.333]     400
(1.333, 3.409]      100
Name: count, dtype: int64

## 7.2.6 Detecting and Filtering Outliers

In [52]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [53]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.071858     0.009361     0.015368    -0.034318
std       1.004973     0.967446     0.979886     1.012673
min      -3.423987    -2.946381    -3.159387    -3.874605
25%      -0.726915    -0.610546    -0.657826    -0.738169
50%      -0.059650    -0.004208     0.004580    -0.067796
75%       0.583527     0.659663     0.685705     0.674703
max       3.623997     3.379721     3.009881     2.550065

In [54]:
col = data[2]

In [55]:
col[col.abs() > 3]

387   -3.159387
397    3.009881
Name: 2, dtype: float64

In [56]:
data[(data.abs() > 3).any(axis='columns')]

            0         1         2         3
149 -3.423987  0.319615  0.230359 -0.894528
219  1.036009  3.126826 -0.031620 -0.237960
267 -1.042786 -0.305504  0.244797 -3.874605
367  3.623997 -0.448137  1.355650 -0.587093
387 -1.364028  0.572400 -3.159387  0.855893
397 -1.382904  2.920730  3.009881 -0.241623
444  1.892317  3.379721 -0.509520  1.396778
466 -3.017017 -0.127292 -0.360504  0.042030
496 -0.150333  3.104605 -1.214490 -0.310255
675  1.508764 -0.245857 -0.203864 -3.002262
709 -0.372533 -0.020653  1.585272 -3.464295
750 -3.279543 -1.668926  2.650958  0.536751

In [57]:
data[data.abs() > 3] = np.sign(data) * 3

In [58]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.071762     0.008750     0.015518    -0.032977
std       1.000631     0.965464     0.979352     1.008246
min      -3.000000    -2.946381    -3.000000    -3.000000
25%      -0.726915    -0.610546    -0.657826    -0.738169
50%      -0.059650    -0.004208     0.004580    -0.067796
75%       0.583527     0.659663     0.685705     0.674703
max       3.000000     3.000000     3.000000     2.550065

In [59]:
np.sign(data).head()

     0    1    2    3
0  1.0 -1.0 -1.0  1.0
1  1.0 -1.0  1.0 -1.0
2  1.0  1.0 -1.0 -1.0
3  1.0 -1.0 -1.0  1.0
4  1.0  1.0 -1.0  1.0

## 7.2.7 Replacement and Random Sampling

In [60]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [61]:
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [62]:
sampler = np.random.permutation(5)

In [63]:
sampler

array([4, 3, 2, 1, 0])

In [64]:
df.take(sampler)

    0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6

In [65]:
df.iloc[sampler]

    0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6

In [67]:
column_sampler = np.random.permutation(7)

In [68]:
column_sampler

array([2, 4, 0, 5, 1, 3, 6])

In [69]:
df.take(column_sampler, axis='columns')

    2   4   0   5   1   3   6
0   2   4   0   5   1   3   6
1   9  11   7  12   8  10  13
2  16  18  14  19  15  17  20
3  23  25  21  26  22  24  27
4  30  32  28  33  29  31  34

In [70]:
df.sample(n=3)

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27

In [71]:
choices = pd.Series([5, 7, -1, 6, 4])

In [72]:
choices.sample(n=10, replace=True)

4    4
1    7
3    6
0    5
4    4
2   -1
2   -1
2   -1
4    4
2   -1
dtype: int64

## 7.2.8 Calculated Metrics/Dummy Variables

In [73]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [74]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [76]:
pd.get_dummies(df['key'])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False