# 10.1 Groupby Mechanism

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'key1' : ['a', 'a', None, 'b', 'b', 'a', None],
                   'key2' : pd.Series([1, 2, 1, 2, 1, None, 1], dtype='Int64'),
                   'data1' : np.random.standard_normal(7),
                   'data2' : np.random.standard_normal(7)
                   })

In [3]:
df

  key1  key2     data1     data2
0    a     1 -0.460488  2.139073
1    a     2  0.043954  0.246307
2  NaN     1  1.705709  0.687334
3    b     2  0.161931  1.029661
4    b     1  1.077109 -0.465935
5    a  <NA>  1.333897 -0.107383
6  NaN     1 -1.317281 -1.541308

In [4]:
grouped = df['data1'].groupby(df['key1']) # groupby() returns a GroupBy object, which is an intermediate object that contains information about the groups but does not yet perform any computations. You can think of it as a "recipe" for how to group the data.

In [5]:
grouped

In [6]:
grouped.mean() # The mean() method is called on the GroupBy object, which triggers the actual computation of the mean for each group. The result is a new Series with the group labels as the index and the computed means as the values.

key1
a    0.305788
b    0.619520
Name: data1, dtype: float64

In [7]:
means = df['data1'].groupby([df['key1'], df['key2']]).mean() # You can also group by multiple keys by passing a list of keys to the groupby() method. The result is a Series with a MultiIndex, where each level of the index corresponds to one of the grouping keys.

In [8]:
means

key1  key2
a     1      -0.460488
      2       0.043954
b     1       1.077109
      2       0.161931
Name: data1, dtype: float64

In [9]:
means.unstack() # The unstack() method is called on the Series with a MultiIndex, which reshapes the data into a DataFrame where one of the levels of the index becomes the columns. This makes it easier to visualize and analyze the grouped data.

key2         1         2
key1
a    -0.460488  0.043954
b     1.077109  0.161931

In [10]:
states = np.array(['OH', 'CA', 'CA', 'OH', 'OH', 'CA', 'OH']) # You can also group by arrays of values, such as a NumPy array. The result is a Series with the array values as the index and the computed means as the values.

In [11]:
years = [2005, 2005, 2006, 2005, 2006, 2005, 2006]

In [12]:
df['data1'].groupby([states, years]).mean() # You can also group by multiple arrays of values, such as a NumPy array and a list. The result is a Series with a MultiIndex, where each level of the index corresponds to one of the grouping keys.

CA  2005    0.688926
    2006    1.705709
OH  2005   -0.149278
    2006   -0.120086
Name: data1, dtype: float64

In [13]:
df.groupby('key1').mean() # You can also group by a single key and compute the mean for all numeric columns in the DataFrame. The result is a new DataFrame with the group labels as the index and the computed means for each numeric column as the values.

      key2     data1     data2
key1
a      1.5  0.305788  0.759332
b      1.5  0.619520  0.281863

In [17]:
df.groupby('key2')[['data1', 'data2']].mean() # You can also group by a single key and compute the mean for all numeric columns in the DataFrame. The result is a new DataFrame with the group labels as the index and the computed means for each numeric column as the values.

         data1     data2
key2
1     0.251262  0.204791
2     0.102943  0.637984

In [18]:
df.groupby(['key1', 'key2']).mean() # You can also group by multiple keys and compute the mean for all numeric columns in the DataFrame. The result is a new DataFrame with a MultiIndex, where each level of the index corresponds to one of the grouping keys, and the computed means for each numeric column as the values.

              data1     data2
key1 key2
a    1    -0.460488  2.139073
     2     0.043954  0.246307
b    1     1.077109 -0.465935
     2     0.161931  1.029661

In [19]:
df.groupby(['key1', 'key2']).size() # The size() method is called on the GroupBy object, which computes the size of each group. The result is a Series with a MultiIndex, where each level of the index corresponds to one of the grouping keys, and the computed sizes for each group as the values.

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [20]:
df.groupby('key1', dropna=False).size() # The dropna parameter is set to False, which means that groups with NaN values in the grouping key will be included in the result. The result is a Series with the group labels as the index and the computed sizes for each group as the values, including a group for NaN values.

key1
a      3
b      2
NaN    2
dtype: int64

In [21]:
df.groupby(['key1', 'key2'], dropna=False).size()

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [22]:
df.groupby('key1').count() # The count() method is called on the GroupBy object, 
# which computes the number of non-NA/null observations in each group. The result is a new DataFrame with the group labels as the index and the computed counts for each column as the values.

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

## 10.1.1 Iterate over the groups

In [23]:
for name, group in df.groupby('key1'):
    print(name)
    print(group)
# The groupby() method can also be used in a for loop to iterate over the groups.
# The result is a sequence of (group name, group DataFrame) pairs, where each group name corresponds to a unique value in the grouping key and each group DataFrame contains the rows of the original DataFrame that belong to that group.

a
  key1  key2     data1     data2
0    a     1 -0.460488  2.139073
1    a     2  0.043954  0.246307
5    a  <NA>  1.333897 -0.107383
b
  key1  key2     data1     data2
3    b     2  0.161931  1.029661
4    b     1  1.077109 -0.465935

In [24]:
for (k1, k2), group in df.groupby(['key1', 'key2']):
    print((k1, k2))
    print(group)
# You can also group by multiple keys and iterate over the groups. The result is a sequence

('a', 1)
  key1  key2     data1     data2
0    a     1 -0.460488  2.139073
('a', 2)
  key1  key2     data1     data2
1    a     2  0.043954  0.246307
('b', 1)
  key1  key2     data1     data2
4    b     1  1.077109 -0.465935
('b', 2)
  key1  key2     data1     data2
3    b     2  0.161931  1.029661

In [25]:
pieces = {name: group for name, group in df.groupby('key1')}
# The groupby() method can also be used in a dictionary comprehension to create a dictionary of DataFrames, where each key is a unique value in the grouping key and each value is the corresponding group DataFrame.

In [26]:
pieces

{'a':   key1  key2     data1     data2
 0    a     1 -0.460488  2.139073
 1    a     2  0.043954  0.246307
 5    a  <NA>  1.333897 -0.107383,
 'b':   key1  key2     data1     data2
 3    b     2  0.161931  1.029661
 4    b     1  1.077109 -0.465935}

In [27]:
pieces['b']

  key1  key2     data1     data2
3    b     2  0.161931  1.029661
4    b     1  1.077109 -0.465935

In [41]:
grouped = df.T.groupby({'key1': 'key', 'key2': 'key',
                     'data1': 'data', 'data2': 'data'}) # You can also group by a mapping of column names to group names, which allows you to group columns instead of rows. The result is a GroupBy object that groups the columns based on the specified mapping.

In [42]:
for group_key, group_values in grouped:
    print(group_key)
    print(group_values)

data
              0         1         2         3         4         5         6
data1 -0.460488  0.043954  1.705709  0.161931  1.077109  1.333897 -1.317281
data2  2.139073  0.246307  0.687334  1.029661 -0.465935 -0.107383 -1.541308
key
      0  1    2  3  4     5    6
key1  a  a  NaN  b  b     a  NaN
key2  1  2    1  2  1  <NA>    1

In [43]:
grouped

## 10.1.2 Select one or more columns

In [44]:
df.groupby(['key1', 'key2'])[['data2']].mean() 
# The groupby() method can also be used to group by multiple keys and select specific columns for aggregation. The result is a new DataFrame with a MultiIndex, where each level of the index corresponds to one of the grouping keys, and the computed means for the selected column as the values.

              data2
key1 key2
a    1     2.139073
     2     0.246307
b    1    -0.465935
     2     1.029661

In [45]:
df

  key1  key2     data1     data2
0    a     1 -0.460488  2.139073
1    a     2  0.043954  0.246307
2  NaN     1  1.705709  0.687334
3    b     2  0.161931  1.029661
4    b     1  1.077109 -0.465935
5    a  <NA>  1.333897 -0.107383
6  NaN     1 -1.317281 -1.541308

In [46]:
s_grouped = df.groupby(['key1', 'key2'])['data2']

In [47]:
s_grouped

In [49]:
s_grouped.mean()

key1  key2
a     1       2.139073
      2       0.246307
b     1      -0.465935
      2       1.029661
Name: data2, dtype: float64

## 10.1.3 Grouping Using Dictionaries and Series

In [51]:
people = pd.DataFrame(np.random.standard_normal((5, 5)),
                      columns=['a', 'b', 'c', 'd', 'e'],
                      index=['Joe', 'Steve', 'Wanda', 'Jill', 'Trey'])

In [52]:
people.iloc[2:3, [1, 2]] = np.nan # Add some NaN values to the DataFrame to demonstrate the effect of the dropna parameter in groupby operations.

In [53]:
people

              a         b         c         d         e
Joe   -0.254714 -0.274534 -1.742325 -0.349230 -0.057911
Steve -1.011915 -0.295223  1.004822  1.180568  2.420778
Wanda  1.559359       NaN       NaN -2.828267  0.104790
Jill  -1.059072  0.472668 -0.977867 -0.039088  1.197888
Trey   0.526592 -0.368200  1.741761 -0.079558  0.866076

In [58]:
mapping = {'a': 'red', 'b': 'red', 'c': 'blue', 'd': 'blue', 'e': 'red', 'f' : 'orange'}

In [59]:
by_column = people.T.groupby(mapping)

In [61]:
by_column.sum().T

           blue       red
Joe   -2.091555 -0.587159
Steve  2.185390  1.113639
Wanda -2.828267  1.664150
Jill  -1.016955  0.611483
Trey   1.662203  1.024468

In [62]:
map_series = pd.Series(mapping)

In [63]:
map_series

a       red
b       red
c      blue
d      blue
e       red
f    orange
dtype: str

In [65]:
people.T.groupby(map_series).count().T

       blue  red
Joe       2    3
Steve     2    3
Wanda     1    2
Jill      2    3
Trey      2    3

## 10.1.4 Grouping Using Functions

In [ ]:
people.groupby(len).sum() # You can also group by the length of the index labels, which allows you to group rows based on the length of their index labels. The result is a new DataFrame with the computed sums for each group as the values.

          a         b         c         d         e
3 -0.254714 -0.274534 -1.742325 -0.349230 -0.057911
4 -0.532481  0.104467  0.763894 -0.118646  2.063964
5  0.547444 -0.295223  1.004822 -1.647698  2.525568

In [67]:
key_list = ['one', 'one', 'one', 'two', 'two']

In [68]:
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one -0.254714 -0.274534 -1.742325 -0.349230 -0.057911
4 two -1.059072 -0.368200 -0.977867 -0.079558  0.866076
5 one -1.011915 -0.295223  1.004822 -2.828267  0.104790

## 10.1.5 Grouping by Index Levels

In [70]:
columns = pd.MultiIndex.from_arrays([['US', 'US', 'US', 'JP', 'JP'],
                                     [1, 3, 5, 1, 3]],
                                     names=['cty', 'tenor'])

In [71]:
hier_df = pd.DataFrame(np.random.standard_normal((4, 5)), columns=columns)

In [72]:
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0     -0.011860  0.317523 -0.348356  0.677443  0.341896
1     -0.510783 -1.153091  0.247916  1.590407 -1.577855
2     -0.482948 -1.362335 -1.429931  1.527583 -1.295492
3     -2.283830 -0.950022 -0.759205  0.673521  1.011772

In [74]:
hier_df.T.groupby(level='cty').count().T

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3