# Base Functions of Series and DataFrame

## 1.Rebuild Index

In [2]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c']) # create a pandas Series with specified index

In [4]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [5]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e']) # reindex the Series to a new index, introducing NaN for missing values

In [6]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [7]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4]) # create a new Series with non-consecutive indices

In [8]:
obj3

0      blue
2    purple
4    yellow
dtype: str

In [9]:
obj3.reindex(np.arange(6), method='ffill') # reindex the Series to a new index range, using forword fill methon to fill missing values

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

In [10]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California']) # create a DataFrame with specified index and columns

In [11]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [12]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd']) # reindex the DataFrame to a new index, introducing NaN for missing values

In [13]:
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [14]:
states = ['Texas', 'Utah', 'California'] # create a list of states

In [15]:
frame.reindex(columns=states) # reindex the DataFrame to a new column order, introducing NaN for missing values

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [16]:
frame.reindex(states, axis='columns') # reindex the DataFrame to a new column order using axis parameter, introducing NaN for missing values

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [17]:
frame.loc[['a', 'd', 'c'], ['California', 'Texas']] # select specific rows and columns from the DataFrame using .loc

   California  Texas
a           2      1
d           8      7
c           5      4

## Drop items on the specified axis

In [18]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e']) # create a new Series with specified index

In [19]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [20]:
new_obj = obj.drop('c') # drop the item with index 'c' from the Series

In [21]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [22]:
obj.drop(['d', 'c']) # drop multiple items from the Series by specifying a list of indices

a    0.0
b    1.0
e    4.0
dtype: float64

In [23]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New york'],
                    columns=['one', 'two', 'three', 'four']) # create a DataFrame

In [24]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [25]:
data.drop(index=['Colorado', 'Ohio']) # drop the rows with specified indices from the DataFrame

          one  two  three  four
Utah        8    9     10    11
New york   12   13     14    15

In [26]:
data.drop(columns=['two']) # drop the column with specified name from the DataFrame

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New york   12     14    15

In [27]:
data.drop('two', axis=1) # drop the column with specified name from the DataFrame using axis parameter

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New york   12     14    15

In [28]:
data.drop(['two', 'four'], axis='columns') # drop multiple columns from the DataFrame by specifying a list of column names and using axis parameter

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New york   12     14

## Indexing, selection, and filtering

In [29]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd']) # create a new Series with specified index

In [30]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [31]:
obj['b'] # select the value at index 'b' from the Series

np.float64(1.0)

In [32]:
obj.iloc[1] # select the value at position 1 from the Series using positional indexing

np.float64(1.0)

In [33]:
obj[2:4] # select a slice of the Series from position 2 to 4 (exclusive)

c    2.0
d    3.0
dtype: float64

In [34]:
obj[['b', 'a', 'd']] # select multiple values from the Series by specifying a list of indices

b    1.0
a    0.0
d    3.0
dtype: float64

In [35]:
obj[[1,3]] # select multiple values from the Series by specifying a list of positions

KeyError: "None of [Index([1, 3], dtype='int64')] are in the [index]"

In [ ]:
obj[obj<2] # select values from the Series that are less than 2 using boolean indexing

a    0.0
b    1.0
dtype: float64

In [ ]:
obj.loc[['b', 'a', 'd']] # select multiple values from the Series using .loc with a list of indices

b    1.0
a    0.0
d    3.0
dtype: float64

In [ ]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1]) # create a new Series with specified index

In [ ]:
obj2 = pd.Series([1, 2, 3], index=['a', 'b', 'c']) # create a new Series with specified index

In [ ]:
obj1

2    1
0    2
1    3
dtype: int64

In [ ]:
obj2

a    1
b    2
c    3
dtype: int64

In [ ]:
obj1[[0, 1, 2]] # select multiple values from the Series by specifying a list of positions

0    2
1    3
2    1
dtype: int64

In [ ]:
obj2[[0, 1, 2]] # select multiple values from the Series by specifying a list of positions

KeyError: "None of [Index([0, 1, 2], dtype='int64')] are in the [index]"

In [ ]:
obj2.loc[[0,1]]

KeyError: "None of [Index([0, 1], dtype='int64')] are in the [index]"

In [ ]:
obj1.iloc[[0, 1, 2]] # select multiple values from the Series by specifying a list of positions using .iloc

2    1
0    2
1    3
dtype: int64

In [ ]:
obj2.iloc[[0, 1, 2]] # select multiple values from the Series by specifying a list of positions using .iloc

a    1
b    2
c    3
dtype: int64

In [ ]:
obj2.loc['b':'c'] # select a slice of the Series from index 'b' to 'c' (inclusive) using .loc

b    2
c    3
dtype: int64

In [ ]:
obj2.loc['b':'c'] = 5 # select a slice of the Series from index 'b' to 'c' (inclusive) using .loc

In [ ]:
obj2

a    1
b    5
c    5
dtype: int64

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four']) # create a DataFrame

In [ ]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data['two'] # select the 'two' column from the DataFrame

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [ ]:
data[['three', 'one']] # select multiple columns from the DataFrame by specifying a list of column names

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [ ]:
data[:2] # select the first two rows of the DataFrame

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [ ]:
data[data['three']>5] # select rows from the DataFrame where the 'three' column is greater than 5

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data < 5 # create a DataFrame of boolean values indicating whether each element in the original DataFrame is less than 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [ ]:
data[data < 5] = 0 # set all values in the DataFrame that are less than 5 to 0

In [ ]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.loc['Colorado'] # select the row with index 'Colorado' from the DataFrame using .loc

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [ ]:
data.loc[['Colorado', 'New York']] # select multiple rows from the DataFrame by specifying a list of indices using .loc

          one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [ ]:
data.loc['Colorado', ['two', 'three']] # select specific rows and columns from the DataFrame using .loc

two      5
three    6
Name: Colorado, dtype: int64

In [ ]:
data.iloc[2] # select the row at position 2 from the DataFrame using .iloc

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [ ]:
data.iloc[2,[3, 0, 1]] # select specific rows and columns from the DataFrame using .iloc

four    11
one      8
two      9
Name: Utah, dtype: int64

In [ ]:
data.iloc[[1, 2], [3, 0, 1]] # select specific rows and columns from the DataFrame using .iloc with lists of positions

          four  one  two
Colorado     7    0    5
Utah        11    8    9

In [ ]:
data.loc[:'Utah', 'two'] # select rows up to 'Utah' and the 'two' column from the DataFrame using .loc

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [ ]:
data.iloc[:,:3][data.three > 5] # select all rows and the first three columns from the DataFrame where the 'three' column is greater than 5 using .iloc and boolean indexing

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [ ]:
data.loc[data.three >= 2] # select all rows from the DataFrame where the 'three' column is greater than or equal to 2 using .loc and boolean indexing

          one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.loc[:,'one'] = 1 # set all values in the 'one' column to 1 using .loc

In [ ]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [ ]:
data.iloc[2] = 5 # select the row at position 2 from the DataFrame using .iloc

In [ ]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [ ]:
data.loc[data['four'] > 5] = 3 # set all rows in the DataFrame where the 'four' column is greater than 5 to 3 using .loc and boolean indexing

In [ ]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [ ]:
data.loc[data.three == 5,'three'] = 6 # set all values in the 'three' column to 6 where the 'three' column is equal to 5 using .loc and boolean indexing

In [ ]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

## 4.arithmetic operations and data alignment

In [36]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e']) # create a new Series with specified index

In [37]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g']) # create a new Series with specifed index

In [38]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [39]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [40]:
s1 + s2 # add the two Series together, aligning by index and introducing NaN for missing values

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [41]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'),index=['Ohio', 'Texas', 'Colorado']) # create a DataFrame with specified index and columns

In [42]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon']) # create a DataFrame with specified index and columns

In [43]:
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [44]:
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [45]:
df1 + df2 # add the two DataFrames together, aligning by index and columns and introducing NaN for missing values

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [46]:
df1 = pd.DataFrame({"A": [1, 2]}) # create a DataFrame with a single column 'A' and two rows

In [47]:
df2 = pd.DataFrame({'B': [3, 4]}) # create a DataFrame with a single column 'B' and two rows

In [48]:
df1

   A
0  1
1  2

In [49]:
df2

   B
0  3
1  4

In [50]:
df1 + df2 # add the two DataFrames together, aligning by index and columns and introducing NaN for missing values

    A   B
0 NaN NaN
1 NaN NaN

In [51]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                   columns=list('abcd')) # create a DataFrame with specified index and columns

In [52]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                   columns=list('abcde')) # create a DataFrame with specified index and columns

In [53]:
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [54]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [55]:
df1 + df2 # add the two DataFrames together, aligning by index and columns and introducing NaN for missing values

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [56]:
df1.add(df2, fill_value=0) # add the two DataFrames together, aligning by index and columns and filling missing values with 0

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [57]:
1 / df1 # element-wise division of the DataFrame by 1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [58]:
df1.rdiv(1) # element-wise division of 1 by the DataFrame

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [61]:
df1.reindex(columns=df2.columns, fill_value=0) # reindex the DataFrame to match the columns of df2, filling missing values with 0

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [62]:
arr = np.arange(12.).reshape((3,4)) # create a NumPy array

In [63]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [64]:
arr[0]

array([0., 1., 2., 3.])

In [65]:
arr - arr[0] # element-wise subtraction of the first row from all rows

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [66]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon']) # create a DataFrame with specified index and columns

In [67]:
series = frame.iloc[0] # select the first row as a Series

In [68]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [69]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [70]:
frame - series # element-wise subtraction of the Series from the DataFrame

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [73]:
series2 = pd.Series(np.arange(3), index=['b', 'e', 'f']) # create a Series with specified index

In [74]:
series2

b    0
e    1
f    2
dtype: int64

In [75]:
frame + series2 # add the Series to the DataFrame, aligning by index and filling missing values with 0

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [76]:
series3 = frame['d'] # select the 'd' column as a Series

In [77]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [78]:
frame.sub(series3, axis='index') # subtract the 'd' column from each row, aligning by index

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [79]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

## 5.function application and mapping

In [80]:
frame = pd.DataFrame(np.random.standard_normal((4,3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon']) # create a DataFrame with random values

In [81]:
frame

               b         d         e
Utah   -1.131037  1.117211  1.516742
Ohio   -0.074074  0.534037  0.254756
Texas  -1.410965  2.105972  0.381395
Oregon  2.710188 -0.275235  0.712196

In [82]:
np.abs(frame)

               b         d         e
Utah    1.131037  1.117211  1.516742
Ohio    0.074074  0.534037  0.254756
Texas   1.410965  2.105972  0.381395
Oregon  2.710188  0.275235  0.712196

In [83]:
def f1(x):
    return x.max() - x.min() # define a function to calculate the range of values in a Series

In [84]:
frame.apply(f1) # apply the function to each column of the DataFrame

b    4.121153
d    2.381207
e    1.261987
dtype: float64

In [85]:
frame.apply(f1, axis='columns') # apply the function to each row of the DataFrame

Utah      2.647779
Ohio      0.608111
Texas     3.516936
Oregon    2.985423
dtype: float64

In [86]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max']) # define a function to calculate the minimum and maximum of values in a Series

In [87]:
frame.apply(f2) # apply the function to each column of the DataFrame

            b         d         e
min -1.410965 -0.275235  0.254756
max  2.710188  2.105972  1.516742

In [88]:
def my_format(x):
    return f'{x:.2f}' # define a function to format a float to two decimal places

In [91]:
frame.map(lambda x: f'{x:.2f}') # apply the function to each element of the DataFrame

            b      d     e
Utah    -1.13   1.12  1.52
Ohio    -0.07   0.53  0.25
Texas   -1.41   2.11  0.38
Oregon   2.71  -0.28  0.71

In [92]:
frame['e'].map(my_format) # apply the function to the 'e' column of the DataFrame

Utah      1.52
Ohio      0.25
Texas     0.38
Oregon    0.71
Name: e, dtype: str

## 6.Sorting and Ranking

In [93]:
obj = pd.Series(np.arange(4), index=['d', 'a', 'b', 'c']) # create a Series

In [94]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [95]:
obj.sort_index() # sort the Series by index

a    1
b    2
c    3
d    0
dtype: int64

In [96]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c']) # create a DataFrame

In [98]:
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [99]:
frame.sort_index() # sort the DataFrame by index

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [100]:
frame.sort_index(axis='columns') # sort the DataFrame by columns

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [101]:
frame.sort_index(axis='columns', ascending=False) # sort the DataFrame by columns in descending order

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [102]:
obj = pd.Series([4, 7, -3, 2]) # create a Series

In [104]:
obj.sort_values() # sort the Series by values

2   -3
3    2
0    4
1    7
dtype: int64

In [105]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2]) # create a Series with NaN values

In [106]:
obj.sort_values() # sort the Series by values, ignoring NaN values

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [107]:
obj.sort_values(na_position='first') # sort the Series by values, placing NaN values at the beginning

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [108]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]}) # create a DataFrame

In [109]:
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [110]:
frame.sort_values('b') # sort the DataFrame by column 'b'

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [111]:
frame.sort_values(['a', 'b']) # sort the DataFrame by columns 'a' and 'b'

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [112]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4]) # create a Series

In [114]:
obj.rank() # rank the Series by values

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [115]:
obj.rank(method='first') # rank the Series by values, placing ties first

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [117]:
obj.rank(ascending=False) # rank the Series by values in descending order

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [118]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]}) # create a DataFrame

In [119]:
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [120]:
frame.rank(axis='columns') # rank the DataFrame by columns

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## 7.axis index with duplicate labels

In [121]:
obj = pd.Series(np.arange(5), index=['a', 'a', 'b', 'b', 'c']) # create a Series with duplicate index labels

In [122]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [123]:
obj.index.is_unique # check if the index is unique

False

In [124]:
obj['a'] # access the value at index label 'a'

a    0
a    1
dtype: int64

In [125]:
obj['c'] # access the value at index label 'c'

np.int64(4)

In [126]:
df = pd.DataFrame(np.random.standard_normal((5,3)),
                  index=['a', 'a', 'b', 'b', 'c']) # create a DataFrame with duplicate index labels

In [127]:
df

          0         1         2
a  0.505338  0.202615 -0.224619
a -0.233739  0.904575  0.980200
b -0.417228  0.198363  0.323477
b -0.317257 -0.454889  0.210827
c -0.467284  1.079757  0.502393

In [128]:
df.loc['b'] # access the row with index label 'b'

          0         1         2
b -0.417228  0.198363  0.323477
b -0.317257 -0.454889  0.210827

In [129]:
df.loc['c'] # access the row with index label 'c'

0   -0.467284
1    1.079757
2    0.502393
Name: c, dtype: float64