In [17]:
import pandas as pd
import numpy as np

In [2]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Neveda', 'Neveda'],
        'year':[2000, 2001, 2002, 2001, 2002, 2003],
        'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} # dictionary
frame = pd.DataFrame(data) # create a dataframe from the dictionary
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Neveda  2002  2.9
5  Neveda  2003  3.2

In [3]:
frame.head() # display the first 5 rows of the dataframe

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Neveda  2002  2.9

In [4]:
frame.tail() # display the last 5 rows of the dataframe

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Neveda  2002  2.9
5  Neveda  2003  3.2

In [5]:
pd.DataFrame(data, columns=['year', 'state', 'pop']) # create a dataframe with specified column order

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Neveda  2.9
5  2003  Neveda  3.2

In [ ]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt']) # create a dataframe with an extra column that is not in the original data

In [7]:
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Neveda  2.9  NaN
5  2003  Neveda  3.2  NaN

In [8]:
frame2.columns # display the column names of the dataframe

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [9]:
frame2['state'] # display the 'state' column of the date frame

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Neveda
5    Neveda
Name: state, dtype: str

In [ ]:
frame2.year # display the 'year' column of the date frame using attribute access

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [11]:
frame2.loc[1] # display the row with index 1

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [12]:
frame2.iloc[2] # display the row with index 2 using integer-location based indexing

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [13]:
frame2['debt'] = 16.5 # assign a scalar value to the entire 'debt' column

In [14]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Neveda  2.9  16.5
5  2003  Neveda  3.2  16.5

In [18]:
frame2['debt'] = np.arange(6.) # assign an array of values to the 'debt' column

In [19]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Neveda  2.9   4.0
5  2003  Neveda  3.2   5.0

In [20]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five']) # create a series with specified index
frame2['debt'] = val # assign the series to the 'debt' column
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Neveda  2.9   NaN
5  2003  Neveda  3.2   NaN

In [ ]:
frame2['eastern'] = frame2['state'] == 'Ohio' # create a new column 'eastern' based on the condition that the 'state' column is equal to 'Ohio'

In [22]:
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Neveda  2.9   NaN    False
5  2003  Neveda  3.2   NaN    False

In [23]:
del frame2['eastern'] # delete the 'eastern' column from the dateframe

In [24]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [25]:
populations = {'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6},
               'Nevada': {2001: 2.4, 2002: 2.9}}

In [26]:
frame3 = pd.DataFrame(populations)

In [27]:
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [28]:
frame3.T # transpose the dataframe

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [29]:
pd.DataFrame(populations, index=[2001, 2002, 2003]) # create a dataframe with specified index

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [30]:
pdata = {"Ohio": frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]} # create a new dictionary with slices of the original dataframe columns

In [31]:
frame3.index.name = 'year' # set the name of the index to 'year'

In [32]:
frame3.columns.name = 'state' # set the name of the columns to 'state'

In [33]:
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [34]:
frame3.to_numpy() # convert the dataframe to a numpy array

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [35]:
frame2.to_numpy() # convert the dataframe to a numpy array

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Neveda', 2.9, nan],
       [2003, 'Neveda', 3.2, nan]], dtype=object)

## Index Objects

In [40]:
obj = pd.Series(np.arange(3), index=['a', 'b', 'c']) # create a pandas Series with default integer index

In [41]:
index = obj.index # create a new index object

In [42]:
index

Index(['a', 'b', 'c'], dtype='str')

In [43]:
index[1:] # slice the index object

Index(['b', 'c'], dtype='str')

In [44]:
index[1] = 'd'  # This will raise an error because Index objects are immutable

TypeError: Index does not support mutable operations

In [45]:
labels = pd.Index(np.arange(3)) # create a new index object with a range of integers

In [46]:
labels

Index([0, 1, 2], dtype='int64')

In [47]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels) # create a pandas Series with a specified index

In [48]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [49]:
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [50]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='str', name='state')

In [51]:
'Ohio' in frame3.columns

True

In [52]:
2003 in frame3.index

False

In [53]:
pd.Index(['foo', 'foo', 'bar', 'bar']) # create a new index object with repeated values

Index(['foo', 'foo', 'bar', 'bar'], dtype='str')