# Base Functions of Series and DataFrame

## 1.Rebuild Index

In [2]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c']) # create a pandas Series with specified index

In [4]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [5]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e']) # reindex the Series to a new index, introducing NaN for missing values

In [6]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [7]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4]) # create a new Series with non-consecutive indices

In [8]:
obj3

0      blue
2    purple
4    yellow
dtype: str

In [9]:
obj3.reindex(np.arange(6), method='ffill') # reindex the Series to a new index range, using forword fill methon to fill missing values

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

In [10]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California']) # create a DataFrame with specified index and columns

In [11]:
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [12]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd']) # reindex the DataFrame to a new index, introducing NaN for missing values

In [13]:
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [14]:
states = ['Texas', 'Utah', 'California'] # create a list of states

In [15]:
frame.reindex(columns=states) # reindex the DataFrame to a new column order, introducing NaN for missing values

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [16]:
frame.reindex(states, axis='columns') # reindex the DataFrame to a new column order using axis parameter, introducing NaN for missing values

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [17]:
frame.loc[['a', 'd', 'c'], ['California', 'Texas']] # select specific rows and columns from the DataFrame using .loc

   California  Texas
a           2      1
d           8      7
c           5      4

## Drop items on the specified axis

In [18]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e']) # create a new Series with specified index

In [19]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [20]:
new_obj = obj.drop('c') # drop the item with index 'c' from the Series

In [21]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [22]:
obj.drop(['d', 'c']) # drop multiple items from the Series by specifying a list of indices

a    0.0
b    1.0
e    4.0
dtype: float64

In [23]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New york'],
                    columns=['one', 'two', 'three', 'four']) # create a DataFrame

In [24]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New york   12   13     14    15

In [27]:
data.drop(index=['Colorado', 'Ohio']) # drop the rows with specified indices from the DataFrame

          one  two  three  four
Utah        8    9     10    11
New york   12   13     14    15

In [28]:
data.drop(columns=['two']) # drop the column with specified name from the DataFrame

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New york   12     14    15

In [29]:
data.drop('two', axis=1) # drop the column with specified name from the DataFrame using axis parameter

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New york   12     14    15

In [30]:
data.drop(['two', 'four'], axis='columns') # drop multiple columns from the DataFrame by specifying a list of column names and using axis parameter

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New york   12     14

## Indexing, selection, and filtering

In [31]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd']) # create a new Series with specified index

In [32]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [33]:
obj['b'] # select the value at index 'b' from the Series

np.float64(1.0)

In [ ]:
obj.iloc[1] # select the value at position 1 from the Series using positional indexing

KeyError: 1

In [35]:
obj[2:4] # select a slice of the Series from position 2 to 4 (exclusive)

c    2.0
d    3.0
dtype: float64

In [37]:
obj[['b', 'a', 'd']] # select multiple values from the Series by specifying a list of indices

b    1.0
a    0.0
d    3.0
dtype: float64

In [38]:
obj[[1,3]] # select multiple values from the Series by specifying a list of positions

KeyError: "None of [Index([1, 3], dtype='int64')] are in the [index]"

In [39]:
obj[obj<2] # select values from the Series that are less than 2 using boolean indexing

a    0.0
b    1.0
dtype: float64

In [40]:
obj.loc[['b', 'a', 'd']] # select multiple values from the Series using .loc with a list of indices

b    1.0
a    0.0
d    3.0
dtype: float64

In [41]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1]) # create a new Series with specified index

In [42]:
obj2 = pd.Series([1, 2, 3], index=['a', 'b', 'c']) # create a new Series with specified index

In [43]:
obj1

2    1
0    2
1    3
dtype: int64

In [44]:
obj2

a    1
b    2
c    3
dtype: int64

In [ ]:
obj1[[0, 1, 2]] # select multiple values from the Series by specifying a list of positions

0    2
1    3
2    1
dtype: int64

In [46]:
obj2[[0, 1, 2]] # select multiple values from the Series by specifying a list of positions

KeyError: "None of [Index([0, 1, 2], dtype='int64')] are in the [index]"

In [47]:
obj2.loc[[0,1]]

KeyError: "None of [Index([0, 1], dtype='int64')] are in the [index]"

In [48]:
obj1.iloc[[0, 1, 2]] # select multiple values from the Series by specifying a list of positions using .iloc

2    1
0    2
1    3
dtype: int64

In [49]:
obj2.iloc[[0, 1, 2]] # select multiple values from the Series by specifying a list of positions using .iloc

a    1
b    2
c    3
dtype: int64

In [50]:
obj2.loc['b':'c'] # select a slice of the Series from index 'b' to 'c' (inclusive) using .loc

b    2
c    3
dtype: int64

In [52]:
obj2.loc['b':'c'] = 5 # select a slice of the Series from index 'b' to 'c' (inclusive) using .loc

In [53]:
obj2

a    1
b    5
c    5
dtype: int64

In [54]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four']) # create a DataFrame

In [55]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [56]:
data['two'] # select the 'two' column from the DataFrame

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [57]:
data[['three', 'one']] # select multiple columns from the DataFrame by specifying a list of column names

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [58]:
data[:2] # select the first two rows of the DataFrame

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [59]:
data[data['three']>5] # select rows from the DataFrame where the 'three' column is greater than 5

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [60]:
data < 5 # create a DataFrame of boolean values indicating whether each element in the original DataFrame is less than 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [61]:
data[data < 5] = 0 # set all values in the DataFrame that are less than 5 to 0

In [62]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [63]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [65]:
data.loc['Colorado'] # select the row with index 'Colorado' from the DataFrame using .loc

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [66]:
data.loc[['Colorado', 'New York']] # select multiple rows from the DataFrame by specifying a list of indices using .loc

          one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [67]:
data.loc['Colorado', ['two', 'three']] # select specific rows and columns from the DataFrame using .loc

two      5
three    6
Name: Colorado, dtype: int64

In [68]:
data.iloc[2] # select the row at position 2 from the DataFrame using .iloc

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [69]:
data.iloc[2,[3, 0, 1]] # select specific rows and columns from the DataFrame using .iloc

four    11
one      8
two      9
Name: Utah, dtype: int64

In [70]:
data.iloc[[1, 2], [3, 0, 1]] # select specific rows and columns from the DataFrame using .iloc with lists of positions

          four  one  two
Colorado     7    0    5
Utah        11    8    9

In [71]:
data.loc[:'Utah', 'two'] # select rows up to 'Utah' and the 'two' column from the DataFrame using .loc

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [72]:
data.iloc[:,:3][data.three > 5] # select all rows and the first three columns from the DataFrame where the 'three' column is greater than 5 using .iloc and boolean indexing

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [73]:
data.loc[data.three >= 2] # select all rows from the DataFrame where the 'three' column is greater than or equal to 2 using .loc and boolean indexing

          one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [74]:
data.loc[:,'one'] = 1 # set all values in the 'one' column to 1 using .loc

In [75]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [77]:
data.iloc[2] = 5 # select the row at position 2 from the DataFrame using .iloc

In [78]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [79]:
data.loc[data['four'] > 5] = 3 # set all rows in the DataFrame where the 'four' column is greater than 5 to 3 using .loc and boolean indexing

In [80]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [81]:
data.loc[data.three == 5,'three'] = 6 # set all values in the 'three' column to 6 where the 'three' column is equal to 5 using .loc and boolean indexing

In [82]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3